name: Make Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install
      run: make install
     
    - name: Lint
      run: make lint
     
